# Generated by Django 4.2.2 on 2023-06-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inp', models.CharField(max_length=200)),
                ('out', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
